# Regenerate the PROCESS comparison files with PROCESS for R (version 5).
#
# Called by tests/fixtures/regenerate.py, which locates Rscript and the PROCESS file. Arguments:
#   1: path to process.R (Hayes's file, downloaded from afhayes.com; never committed)
#   2: repository root
#   3: output directory (tests/Results/v5)
#   4: comma-separated model numbers
#   5: comma-separated outcomes among ols,logit
#   6: "force" to overwrite existing files, anything else to skip them
#
# One file per model and outcome, named like the 2.16 files: Results_OLS_ModelN.txt, Results_Logit_ModelN.txt.
# Options mirror the accuracy tests: 5000 bootstrap resamples, seed 123456, total and contrast effects,
# HC3 standard errors, six decimals, and intprobe = 1 so that conditional effects are printed whatever the
# p-value of the interaction (PROCESS 5 probes only below 0.10 by default; PyProcessMacro always reports them). Effect sizes are requested for the unmoderated mediation models 4 and 6
# with a continuous outcome. PROCESS 5 has no third or fourth moderator, so models that need one (23 to 27
# and 30 to 57 in the 2.16 numbering) are skipped with a note in the log, as is model 74, which PROCESS 5
# rejects as an invalid model number.

args <- commandArgs(trailingOnly = TRUE)
process_r <- args[1]
root <- args[2]
out_dir <- args[3]
models <- as.integer(strsplit(args[4], ",")[[1]])
outcomes <- strsplit(args[5], ",")[[1]]
force <- identical(args[6], "force")

invisible(capture.output(source(process_r)))
dir.create(out_dir, showWarnings = FALSE, recursive = TRUE)

moderator_symbols <- c("w", "z", "v", "q")

not_in_process_5 <- c(74)

for (model in models) {
  if (model %in% not_in_process_5) {
    cat(sprintf("model %d: skipped, not a model in PROCESS 5\n", model))
    next
  }
  data <- read.csv(file.path(root, "tests", "Data", sprintf("Data_Model%d.csv", model)))
  varlist <- strsplit(readLines(file.path(root, "tests", "Data", sprintf("Varlist_Model%d.txt", model)), warn = FALSE)[1], ",")[[1]]
  varlist <- trimws(varlist)

  if (model <= 3) {
    mediators <- NULL
    moderators <- c("m", intersect(c("w", "z"), varlist))  # PROCESS 2.16 called the first moderator M; 5 calls it W
  } else {
    mediators <- intersect(c("m1", "m2"), varlist)
    if (length(mediators) == 0) mediators <- "m"
    moderators <- intersect(moderator_symbols, varlist)
  }
  if (length(moderators) > 2) {
    cat(sprintf("model %d: skipped, %d moderators (%s) and PROCESS 5 has W and Z only\n",
                model, length(moderators), paste(moderators, collapse = ",")))
    next
  }

  for (outcome in outcomes) {
    y <- if (outcome == "logit") "y2" else "y"
    label <- if (outcome == "logit") "Logit" else "OLS"
    out_file <- file.path(out_dir, sprintf("Results_%s_Model%d.txt", label, model))
    if (file.exists(out_file) && !force) {
      cat(sprintf("model %d %s: exists, skipped\n", model, label))
      next
    }
    call_args <- list(data = data, y = y, x = "x", model = model, boot = 5000, seed = 123456,
                      total = 1, contrast = 1, hc = 3, intprobe = 1, decimals = 10.6, progress = 0)
    if (!is.null(mediators)) call_args$m <- mediators
    if (length(moderators) >= 1) call_args$w <- moderators[1]
    if (length(moderators) >= 2) call_args$z <- moderators[2]
    if (model %in% c(4, 6) && outcome == "ols") call_args$effsize <- 1
    # PROCESS 5.0 fails with "object dfres not found" when it probes a three-way interaction for a
    # logistic outcome, so model 3 with the binary outcome keeps the default probing threshold.
    if (model == 3 && outcome == "logit") call_args$intprobe <- NULL

    started <- Sys.time()
    header <- c(
      sprintf("# Generated by tests/fixtures/regenerate.R with PROCESS for R version 5.0 on %s", format(started, "%Y-%m-%d")),
      sprintf("# Call: process(data=Data_Model%d.csv, %s)", model,
              paste(sprintf("%s=%s", names(call_args)[-1],
                            sapply(call_args[-1], function(v) paste(deparse(v), collapse = ""))), collapse = ", ")),
      ""
    )
    output <- tryCatch(
      capture.output(do.call(process, call_args)),
      error = function(e) c("PROCESS ERROR", conditionMessage(e))
    )
    writeLines(c(header, output), out_file)
    cat(sprintf("model %d %s: %d lines in %.0fs%s\n", model, label, length(output),
                as.numeric(difftime(Sys.time(), started, units = "secs")),
                if (any(grepl("PROCESS ERROR", output))) " (PROCESS ERROR)" else ""))
  }
}
