# Regenerate the multicategorical comparison files with PROCESS for R (version 5), issue #17.
#
# Called by tests/fixtures/regenerate.py --suite mc. Arguments:
#   1: path to process.R (Hayes's file; never committed)
#   2: repository root
#   3: output directory (tests/Results/v5/mc)
#   4: comma-separated case ids among those in CASES below, or "all"
#   5: "force" to overwrite existing files, anything else to skip them
#
# Options mirror the other comparison files: 5000 bootstrap resamples, seed 123456, total effects, HC3 standard
# errors, six decimals, intprobe = 1. The contrast option is not available with a multicategorical X in PROCESS,
# so it is not used. Data: tests/Data/Data_MC.csv (tests/fixtures/make_mc_data.py).

args <- commandArgs(trailingOnly = TRUE)
process_r <- args[1]
root <- args[2]
out_dir <- args[3]
wanted <- strsplit(args[4], ",")[[1]]
force <- identical(args[5], "force")

invisible(capture.output(source(process_r)))
dir.create(out_dir, showWarnings = FALSE, recursive = TRUE)
data <- read.csv(file.path(root, "tests", "Data", "Data_MC.csv"))

# id, model, x, w, m (comma-separated), mcx, mcw, y
CASES <- list(
  list(id = "m4_mcx1", model = 4, x = "xcat", w = NA, m = "m", mcx = 1, mcw = 0, y = "y"),
  list(id = "m4_mcx2", model = 4, x = "xcat", w = NA, m = "m", mcx = 2, mcw = 0, y = "y"),
  list(id = "m4_mcx3", model = 4, x = "xcat", w = NA, m = "m", mcx = 3, mcw = 0, y = "y"),
  list(id = "m4_mcx4", model = 4, x = "xcat", w = NA, m = "m", mcx = 4, mcw = 0, y = "y"),
  list(id = "m4_2m_mcx1", model = 4, x = "xcat", w = NA, m = "m,m2", mcx = 1, mcw = 0, y = "y"),
  list(id = "m4_logit_mcx1", model = 4, x = "xcat", w = NA, m = "m", mcx = 1, mcw = 0, y = "y2"),
  list(id = "m6_mcx1", model = 6, x = "xcat", w = NA, m = "m,m2", mcx = 1, mcw = 0, y = "y"),
  list(id = "m1_mcx1", model = 1, x = "xcat", w = "w", m = NA, mcx = 1, mcw = 0, y = "y"),
  list(id = "m1_mcx3", model = 1, x = "xcat", w = "w", m = NA, mcx = 3, mcw = 0, y = "y"),
  list(id = "m1_mcw1", model = 1, x = "x", w = "wcat", m = NA, mcx = 0, mcw = 1, y = "y"),
  list(id = "m1_mcw3", model = 1, x = "x", w = "wcat", m = NA, mcx = 0, mcw = 3, y = "y"),
  list(id = "m1_mcx1_mcw1", model = 1, x = "xcat", w = "wcat", m = NA, mcx = 1, mcw = 1, y = "y"),
  list(id = "m1_logit_mcx1", model = 1, x = "xcat", w = "w", m = NA, mcx = 1, mcw = 0, y = "y2"),
  list(id = "m5_mcx1", model = 5, x = "xcat", w = "w", m = "m", mcx = 1, mcw = 0, y = "y"),
  list(id = "m7_mcx1", model = 7, x = "xcat", w = "w", m = "m", mcx = 1, mcw = 0, y = "y"),
  list(id = "m7_mcx3", model = 7, x = "xcat", w = "w", m = "m", mcx = 3, mcw = 0, y = "y"),
  list(id = "m7_mcw1", model = 7, x = "x", w = "wcat", m = "m", mcx = 0, mcw = 1, y = "y"),
  list(id = "m7_mcw3", model = 7, x = "x", w = "wcat", m = "m", mcx = 0, mcw = 3, y = "y"),
  list(id = "m4_mcx1_hc0", model = 4, x = "xcat", w = NA, m = "m", mcx = 1, mcw = 0, y = "y", hc = 5),
  list(id = "m8_mcx1", model = 8, x = "xcat", w = "w", m = "m", mcx = 1, mcw = 0, y = "y"),
  list(id = "m8_mcw1", model = 8, x = "x", w = "wcat", m = "m", mcx = 0, mcw = 1, y = "y"),
  list(id = "m14_mcx1", model = 14, x = "xcat", w = "w", m = "m", mcx = 1, mcw = 0, y = "y"),
  list(id = "m14_mcw1", model = 14, x = "x", w = "wcat", m = "m", mcx = 0, mcw = 1, y = "y"),
  list(id = "m58_mcx1", model = 58, x = "xcat", w = "w", m = "m", mcx = 1, mcw = 0, y = "y")
)

for (case in CASES) {
  if (!("all" %in% wanted) && !(case$id %in% wanted)) next
  out_file <- file.path(out_dir, sprintf("%s.txt", case$id))
  if (file.exists(out_file) && !force) {
    cat(sprintf("%s: exists, skipped\n", case$id))
    next
  }
  call_args <- list(data = data, y = case$y, x = case$x, model = case$model, boot = 5000, seed = 123456,
                    total = 1, hc = 3, intprobe = 1, decimals = 10.6, progress = 0)
  if (!is.na(case$m)) call_args$m <- strsplit(case$m, ",")[[1]]
  if (!is.na(case$w)) call_args$w <- case$w
  if (case$mcx > 0) call_args$mcx <- case$mcx
  if (case$mcw > 0) call_args$mcw <- case$mcw
  if (!is.null(case$hc)) call_args$hc <- case$hc
  started <- Sys.time()
  header <- c(
    sprintf("# Generated by tests/fixtures/regenerate_mc.R with PROCESS for R version 5.0 on %s", format(started, "%Y-%m-%d")),
    sprintf("# Call: process(data=Data_MC.csv, %s)",
            paste(sprintf("%s=%s", names(call_args)[-1],
                          sapply(call_args[-1], function(v) paste(deparse(v), collapse = ""))), collapse = ", ")),
    ""
  )
  output <- tryCatch(
    capture.output(do.call(process, call_args)),
    error = function(e) c("PROCESS ERROR", conditionMessage(e))
  )
  writeLines(c(header, output), out_file)
  cat(sprintf("%s: %d lines in %.0fs%s\n", case$id, length(output),
              as.numeric(difftime(Sys.time(), started, units = "secs")),
              if (any(grepl("PROCESS ERROR", output))) " (PROCESS ERROR)" else ""))
}
